# Generated by Django 5.2.15 on 2026-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
    ]
