# Generated by Django 5.2.15 on 2026-06-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_user_is_typing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
